### ISSUE TITLE
Multiplayer doesn't work

### ISSUE THREAD

**Issue by mrkylegp** [Carlmundo/W2-Plus#1]
Can't get the multiplayer working.

Have port forwarded everything correctly and I'm able to create a room and a game. The other person can join the room and see the game, but when attempting to connect to the game it just says "Now searching for a worms 2 game" indefinitely.

Any ideas?

**Comment by Carlmundo** [comment]
Come join the Discord and see if we can help troubleshoot with you:
https://discord.gg/CygRQprEtg

**Comment by Remy784** [comment]
I also can't get the multiplayer working.

The button in the main menu isn't grayed out. I can press it, but when I do it, the game crashes and the game window closes. The multiplayer window doesn't open. I tried to do port forwarding in my FritzBox Router and also gave the game in my Windows Defender Firewall "full access". Nothing works.
The event display of Windows 10 shows following error when pressing the network button:

Name der fehlerhaften Anwendung: frontend.exe, Version: 1.0.1.5, Zeitstempel: 0x3528dcb1
Name des fehlerhaften Moduls: fkNetcode.dll, Version: 1.0.1.0, Zeitstempel: 0x5f105ce6
Ausnahmecode: 0xc0000409
Fehleroffset: 0x00001f3a
ID des fehlerhaften Prozesses: 0x2c94
Startzeit der fehlerhaften Anwendung: 0x01d7edead96f42d3
Pfad der fehlerhaften Anwendung: E:\Worms 2\frontend.exe
Pfad des fehlerhaften Moduls: E:\Worms 2\fkNetcode.dll
Berichtskennung: c7728463-481c-4ed9-acf3-d9e5c1bf505b
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by mrkylegp** [comment]
Multiplayer works for me now. It should be noted that all players need to port forward on their end, even if they are only joining and not hosting. Once my friends also port forwarded, they were able to join. I recommend adding this to the docs @Carlmundo

**Comment by Carlmundo** [comment]
Just to note, there were a bunch of multiplayer bugs that have now been fixed in the latest version.
