### ISSUE TITLE
"Qt: Untested Windows version 6.2 detected!"

### ISSUE THREAD

**Issue by HeyItsLollie** [Carlmundo/W2-Plus#10]
When launching Worms 2 with W2-Plus v1.5.6 installed, the Command Line window will display the message:
"Qt: Untested Windows version 6.2 detected!"

Explorer (and as a result, the Start Bar) will then freeze. Sometimes it restarts on its own, but otherwise Task Manager must be opened to restart Explorer manually. The game itself runs without any issue!

In addition: GOG Launcher will occasionally, but not always, display this message. Selecting "No" allows Worms 2 to continue normally.
![GOGLauncher - 2023-10-21 - 16-20-35](https://github.com/Carlmundo/W2-Plus/assets/30498581/c2ce3c83-e7d4-46cf-8ae9-6a5f1c5e3fb7)

Windows 11 Pro, Version 22H2, Build 22621.2428
Worms 2 via GOG, using W2-Plus v1.5.6.

**Comment by Carlmundo** [comment]
Hello. So the GOG Launcher for Worms 2 is very broken on modern versions of Windows. Please start the game by running either start.exe or frontend.exe and let me know if that works. There should be Desktop shortcuts for these too.

**Comment by HeyItsLollie** [comment]
That was it, thank you!

Posting the information below for anyone else who encounters this issue when launching Worms 2 via GOG Galaxy.

For convenience, I've modified how Worms 2 launches via GOG Galaxy by:
- Clicking the "More" settings dropdown button, and navigating to Manage Installation > Configure...

<img width="362" alt="GalaxyClient - 2023-11-11 - 13-47-46" src="https://github.com/Carlmundo/W2-Plus/assets/30498581/8c5a33c5-1949-4ab0-8922-95632cb6098f">

- Under Features, adding Start.exe (play with intro videos) or Frontend.exe (skip intro videos) as a new executable, and setting it as the default executable.

<img width="380" alt="GalaxyClient - 2023-11-11 - 13-48-52" src="https://github.com/Carlmundo/W2-Plus/assets/30498581/3f55aba7-7ea8-4b09-b528-3896035eb3c8">
<br>
<img width="380" alt="GalaxyClient - 2023-11-11 - 13-50-44" src="https://github.com/Carlmundo/W2-Plus/assets/30498581/cfb913e0-b66a-45ce-a8c2-444efcaf0850">

Pressing "Play" in GOG Galaxy will now always bypass the default and broken GOGLauncher.exe, and open Worms 2 directly.
