### ISSUE TITLE
Game displayed in one corner of the screen

### ISSUE THREAD

**Issue by vmatkov** [Carlmundo/W2-Plus#11]
After installation of the Worms 2 Plus package the game is only displayed in one corner of the screen.
Any fix for this?

Example:
![slika](https://github.com/Carlmundo/W2-Plus/assets/15020076/eb39bd7d-b494-4063-a4bc-9f4d7d86730c)

**Comment by discobean** [comment]
I have the same issue, I found sometimes it works, other times it doesn't.  I need to restart multiple times until it just works randomly.  Very unusual.

**Comment by Carlmundo** [comment]
Hello, unfortunately there isn't a way around this for cavern maps. As a workaround, you can zoom in with the mouse wheel to fill the screen.

**Comment by Carlmundo** [comment]
@vmatkov @discobean - Looking into this again. What resolutions are you running at?

**Comment by discobean** [comment]
Hi @Carlmundo, the resolution is on a tv, 4k, 3840 x 2160 on Windows 11, the Scale and layout of the screen is set to 150%

**Comment by vmatkov** [comment]
> @vmatkov @discobean - Looking into this again. What resolutions are you running at?

Hi, I'm using my Laptop with the resolution 2560x1600.

**Comment by Carlmundo** [comment]
@vmatkov @discobean I have released a beta update that should improve this issue:
 https://github.com/Carlmundo/W2-Plus/releases/tag/1.5.8beta

When installing, please check this option to test it:
![image](https://github.com/Carlmundo/W2-Plus/assets/472397/637dc9b1-7115-469f-b1eb-0f175b580ed0)

**Comment by Carlmundo** [comment]
@vmatkov @discobean - This is now implemented in the latest release.
