### ISSUE TITLE
crashes with lutris wine gog install in linux

### ISSUE THREAD

**Issue by bitclick** [Carlmundo/W2-Plus#13]
System:
- Ubuntu 20.04 
- lutris-0.5.16  with wine-ge-8-26-x86_64
- window managers tested:  xmonad, xfce4
- worms2 from gog
- worms2plus  v1.5.8

# problem
- installation gave no errors
- worm2 gog worked fine
- starting worms2plus  via `frontend.exe`
- game is not starting, no black screen, window etc.
- after less than 1 sec it terminates
- lutris log:
```
wine client error:118: Monitored process exited.
Initial process has exited (return code: 0)
Exit with return code 0
```

# workaround
- it works when i switch lutris to system wine `wine-5.0 (Ubuntu 5.0-3ubuntu1)`

# question
- how to install this with good odds to have it working?
- could there be an install-script for lutris (with known-good dependencies etc.)?

**Comment by Carlmundo** [comment]
Hello @bitclick, I don't have experience with Lutris but try seeing if frontend.exe will start with the following files moved out of the game folder:

- fkDRP.dll
- fkNetcode.dll
- fkUpdate.dll

If that works, then try to isolate and figure out which dll is causing the issue and let me know.

**Comment by bitclick** [comment]
> try seeing if frontend.exe will start with the following files moved out of the game folder:
> 
> * fkDRP.dll
> * fkNetcode.dll
> * fkUpdate.dll

no change. I removed `fkNetcode.dll` and `fkUpdate.dll`. `fkDRP.dll` was not present in the game folder.

**Comment by bitclick** [comment]
> > try seeing if frontend.exe will start with the following files moved out of the game folder:
> > 
> > * fkDRP.dll
> > * fkNetcode.dll
> > * fkUpdate.dll
> 
> no change. I removed `fkNetcode.dll` and `fkUpdate.dll`. `fkDRP.dll` was not present in the game folder.

update: 
- i did a fresh install and all dlls including `fkDRP.dll` is present
- it works when i run `start.exe` instead of `frontend.exe` (the latter still exiting immediately)

so this could be closed
