### ISSUE TITLE
Game just crashes after updating to v1.5.8.2

### ISSUE THREAD

**Issue by floppyD** [Carlmundo/W2-Plus#14]
After messing around I found that the issue was in wndmode.ini, UseDirectDraw=1 would cause a crash when starting matches. Setting it to 0 and UseDirect3D=1 worked.

Windows 10 22H2 and latest Nvidia drivers, if it's relevant.

**Comment by Carlmundo** [comment]
A new update has released.

Can you please install it and follow these steps:

1. Launch the game.
2. Go into options.
3. Click the new "Advanced options" button.
4. Set the resolution/settings to your liking.
5. Start the game and see if the issue from before happens again.

**Comment by floppyD** [comment]
Just installed 1.6 on top of a clean Worms 2 install, didn't need to change anything, worked fine.
