### ISSUE TITLE
Weird ninja rope behavior in 1.6

### ISSUE THREAD

**Issue by floppyD** [Carlmundo/W2-Plus#15]
No settings changed, installed on top of a clean install. Mission 35 - DIDNTHAVETIMETO
1.5.8.2 doesn't have this issue.

[asd.webm](https://github.com/Carlmundo/W2-Plus/assets/29208110/d50dd9a9-d218-4d84-8ce0-c4711c0bcb2c)

**Comment by Carlmundo** [comment]
@floppyD is that Brazilian Portuguese? And were you using the same language in 1.6 and 1.5.8.2?

**Comment by floppyD** [comment]
Yes, for both.

**Comment by Carlmundo** [comment]
Unfortunately, the original game has issues with the rope at certain angles. I am able to replicate this issue in 1.5.8.2 and 1.6. Sometimes it happens and sometimes it does not.

There is a rope fix that may improve this specific situation but it is not stable and cause some people to crash.

**Comment by floppyD** [comment]
I swear I could reproduce this consistently when I reported, and I tried at least 10 times, but I couldn't trigger it once now, be it in 1.5.8.2 or 1.6. On top of that I got a BSOD when trying lol

But since it's just a game bug, let's leave it at that. Thanks for the patch by the way, it's really good finally being able to play W2 on modern hardware with little to no issues.

**Comment by Carlmundo** [comment]
@floppyD This was fixed in the latest release.
