### ISSUE TITLE
cnc-ddraw settings - copy cnc-ddraw config behavior

### ISSUE THREAD

**Issue by FunkyFr3sh** [Carlmundo/W2-Plus#16]
When "Borderless" was selected in the config it should also set these values:

```
toggle_borderless = true
toggle_upscaled = false
```

When "Fullscreen" was selected in the config it should also set these values:

```
toggle_borderless = false
toggle_upscaled = true
```

"Windowed" mode should probably use the same settings as borderless, (but it's personal preference though)
```
toggle_borderless = true
toggle_upscaled = false
```

Might also be a good idea to default to opengl for higher quality upscaling

```
renderer=opengl
shader=Bicubic
```

Or maybe add the shader settings to the config as well?

`Nearest neighbor, Bilinear, Bicubic, Lanczos, xBR-lv2`

**Comment by Carlmundo** [comment]
Fixed and will be included in the next released.
