### ISSUE TITLE
Feature request - Save mission progress on exit

### ISSUE THREAD

**Issue by Willicious** [Carlmundo/W2-Plus#17]
Typing the passwords is OK and all, but some sort of system that remembers the progress of a particular team, saves on exiting and loads on starting mission would be a good addition to W2+

**Comment by Carlmundo** [comment]
Thanks for the suggestion but unfortunately this isn't something I would know how to implement.

**Comment by Willicious** [comment]
Maybe I can have a go at it myself. I'd need to know a few things if you don't mind sharing:

a) what language is the patch code written in?
b) what IDE  / environment / software did you use to compile?
c) any tips on getting it to build?

**Comment by Carlmundo** [comment]
The patch is comprised of many different modules. Your request would require reverse engineering. It may be better to discuss your request on the Discord to see if anyone else has a good idea on how to go about doing it.

**Comment by Carlmundo** [comment]
@Willicious - This feature will be avaialble in a future patch.

**Comment by Carlmundo** [comment]
@Willicious - This feature is now available in the latest release.

**Comment by Willicious** [comment]
Hi Carlmundo, thanks for implementing this! 😊👍

**Comment by Carlmundo** [comment]
@Willicious No problem, but this was the work of Dawid8 :)
