### ISSUE TITLE
TEAM17MicroProse cheat doesn't work in mission mode

### ISSUE THREAD

**Issue by Willicious** [Carlmundo/W2-Plus#18]
Naming the team TEAM17MicroProse when in mission mode doesn't apply all weapons:

![image](https://github.com/Carlmundo/W2-Plus/assets/76848857/a682c6ba-fb3f-44a3-9e7c-64635fb3c2ee)

![image](https://github.com/Carlmundo/W2-Plus/assets/76848857/6d5c9b91-2417-4e07-8082-2945747796f0)

**Comment by Carlmundo** [comment]
The cheat has never worked in mission mode.
