### ISSUE TITLE
Bug Report - Ninja Rope not functioning proper when used on the ground.

### ISSUE THREAD

**Issue by DrEngineer1** [Carlmundo/W2-Plus#19]
I have played this on a older patch of W2-Plus and ninja rope did function on the ground but only at certain angles. now it appears to not function at all on the ground. only in the air. Not sure if it's because of the game or W2-Plus acting weird.

https://github.com/user-attachments/assets/91a4dfcc-a8e4-4b5f-a5a4-25a54a5d6efd

**Comment by Carlmundo** [comment]
@DrEngineer1 Do you remember which old version you had?

**Comment by DrEngineer1** [comment]
I Believe I do yes. The version was either v1.5.1 or v1.05 for sure iirc.

**Comment by Carlmundo** [comment]
@DrEngineer1 - This will be addressed in the next patch. Possibly in a week or so.

**Comment by Carlmundo** [comment]
@DrEngineer1 - This is now fixed in the latest release.
