### ISSUE TITLE
Single player mission crash

### ISSUE THREAD

**Issue by luismglvieira** [Carlmundo/W2-Plus#2]
Hi, thanks for taking the time to fix this awesome game that I played intensively during my childhood.

I'm using Manjaro with wine-staging 7.4 since that was the only wine version that worked for me.

Still, at the end of a single player mission campaign, the game crashes.

Also crashes at alt-tab, but that would be another, and minor, issue.

Thanks in advance!

**Comment by Carlmundo** [comment]
Hello,

Is this still an issue?

**Comment by Carlmundo** [comment]
Just released an update that should improve stability for English, Portuguese and some other languages.
