### ISSUE TITLE
A minimal version 

### ISSUE THREAD

**Issue by Azarien** [Carlmundo/W2-Plus#20]
There should be a minimal release or installation option(s) that only fixes bugs and compatibility/network issues but tries not to alter the original gameplay and especially doesn't add any new content like soundbanks or "improved" music and videos.

**Comment by Carlmundo** [comment]
Hi @Azarien, this isn't something I'm thinking of doing right now.
However, I think I can see what you're going for and if there's interest then I could look into it after the next release which has a big focus on playing online without port forwarding.
