### ISSUE TITLE
Space bar causes program crash

### ISSUE THREAD

**Issue by Willicious** [Carlmundo/W2-Plus#22]
Since installing the latest version, pressing the spacebar causes the program to crash.

**Comment by Carlmundo** [comment]
@Willicious Currently working on a fix for this. Will be released soon.

**Comment by Carlmundo** [comment]
@Willicious - Please install the latest release :) https://github.com/Carlmundo/W2-Plus/releases/latest

**Comment by Willicious** [comment]
Confirmed, it's now fixed. Thanks!
