### ISSUE TITLE
I can't create CPU Teams (Version v1.6.2.1 )

### ISSUE THREAD

**Issue by Zerodarkage** [Carlmundo/W2-Plus#23]
Hi! Since the last update I can't create CPU Teams! If I create one they become a Human Team! I'm doing something wrong!?
Here:
![image](https://github.com/user-attachments/assets/576d92a8-6a9a-4f5f-a5d3-7f4d61ffcfbc)
Thanks in advance!

P.S.
The "FIX" (Or is this normal!?)
Create 2 Human Teams!
Make 1 random CPU Team!
Delete 1 Human Team!
Problem solved!

**Comment by Carlmundo** [comment]
I wasn't able to recreate this. In the screenshot it seems that you were editing a team, where you can't change the type to CPU.

**Comment by Zerodarkage** [comment]
> I wasn't able to recreate this. In the screenshot it seems that you were editing a team, where you can't change the type to CPU.

Well! I can test with the latest release real fast! :D

Yessss!!! You fixed it!!!
Now I don't need two Human Teams to create a CPU Team!!!
Thank you very much!!!
