### ISSUE TITLE
Feature Request - More Weapon Scheme Options

### ISSUE THREAD

**Issue by DrEngineer1** [Carlmundo/W2-Plus#24]
I am not sure if this is possible due to the information of the scheme being sent to the main game executable which has not been found so far to allow much in modifications as we know. But I think there could be some additional scheme options for some weapons such as:
- Ninja Rope: Rope Length
- All Super Weapons: Now can be modified for damage, crater damage, etc. except for crate probability.

As for all of the weapons there could be an option toggle within them to assign them as a super weapon. Which overrides crate probability and puts it into the list of randomly selected super weapons when a super weapon is selected for the crate drop. This can be a very nice option for those that wish to put weapons such as Super Banana Bomb or Ming Vase as super weapons or super weapons like the Confused Sheep Strike as normal weapons. Basically, creating a nice balancing option for weapon schemes.

**Comment by Carlmundo** [comment]
I would love to have the settings for super weapons editable in the frontend. Unfortunately, it's not something that I'm able to implement myself. 

However, some of what you're asking (schemes with super weapons enabled) is possible with "Worms 2 Super Editor" and potentially another project that may be avaialble in the future.
