### ISSUE TITLE
the game crashes as i press fire button 

### ISSUE THREAD

**Issue by mahnader** [Carlmundo/W2-Plus#3]
when i press fire button  the games crashes . any solution ?  
i have windows 10

**Comment by spudpiggy** [comment]
This is caused by some of the des patches that are applied to worms2.exe. I have made Carl aware of this issue and hopefully he will push an update fixing this.

**Comment by Carlmundo** [comment]
Fixed in the new release.

**Comment by spudpiggy** [comment]
Update on this issue: the 'rope fix' that was originally causing this crash has been replaced with one that works and doesn't crash the game, at least for me.
Next update will include this
