### ISSUE TITLE
"Cannot host your game. Please use Worms 2 Plus and check your configuration. More information at worms2.highog.com"

### ISSUE THREAD

**Issue by sudodebian** [Carlmundo/W2-Plus#4]
Hello im trying to host a game for testing, when im trying this error comes out of the blue:

![image](https://user-images.githubusercontent.com/108587751/183986823-724bd29d-f353-4888-a873-eea0eb3faa33.png)

This is really weird since i do have Worms 2 Plus installed in my computer, it does seems to happen for other pepole as an certain user in the Worms 2 discord server had the same error as mine.

Any fixes ?
Thanks

**Comment by Carlmundo** [comment]
Please try this with the latest version now.

**Comment by sudodebian** [comment]
> Please try this with the latest version now.

Hey sorry, for the late response, but i can't confirm that it now does indeed works. Did the older version needed a port to be opened ? since i still didn't changed my router.
![image](https://github.com/Carlmundo/W2-Plus/assets/108587751/dc4f3fde-2097-4e49-a0eb-df017c91afe4)

Anyways, Thanks !
