### ISSUE TITLE
Ingame Dutch language issue.

### ISSUE THREAD

**Issue by TheDutchBiscuit** [Carlmundo/W2-Plus#5]
First of all, i want to thank you so much CarlMundo for releasing this great patch.
I did buy the worms 2 game form gog and after this patch it works fine.

I did installed it as the Dutch version and it displays the Dutch texts as intended.

But when you are ingame, the texts are in english!
I mean when a worm dies or when a crate is dropped.
This also should be in Dutch.

Is there a file im missing in order to fix this minor issue?
Hope to hear from you soon,

The Dutch Biscuit, 
rf.koek@gmail.com

**Comment by Carlmundo** [comment]
This should now be fixed in the new release.
