### ISSUE TITLE
Audio Mixer Volume greyed out under Audio Options

### ISSUE THREAD

**Issue by uppermezzanine** [Carlmundo/W2-Plus#7]
I am unable to click to change the volume of effects and music, and unfortunately by default the music plays much too loudly to hear the effects and voices sufficiently.

**Comment by Carlmundo** [comment]
Unfortunately there is no way to change this at present. It is intended to open the Volume Mixer from Windows 9x which of course doesn't exist in modern Windows.

**Comment by Carlmundo** [comment]
Actually, I now have a workaround for this that I will release soon

**Comment by Carlmundo** [comment]
A new release is avaialble. To change the volume, just edit volumeBGM.txt with a value between 0 and 100.

**Comment by Carlmundo** [comment]
Re-opening this as there is a work in progress.

**Comment by Carlmundo** [comment]
@uppermezzanine This is now included in the beta release: https://github.com/Carlmundo/W2-Plus/releases/tag/1.5.8beta
and will also be in the next stable release.

**Comment by Carlmundo** [comment]
@uppermezzanine - This has now been implemented into the latest release.

**Comment by uppermezzanine** [comment]
Fantastic job. Thank you for your dedication and hard work!
