### ISSUE TITLE
Please properly credit the "Classic - Director's Cut" speechbank

### ISSUE THREAD

**Issue by BenPaddon** [Carlmundo/W2-Plus#8]
Hello! I'm Ben, also known in the community as Squirminator2k. I'm the person who originally went to the effort of converting the English speechbanks from Worms and Worms: The Director's Cut on the Amiga for use in W2/WA/WWP.

I would appreciate it immensely if I were properly credited for this conversion, and if you could also credit Andy Davidson (who voices the English speechbank in the Amiga version).

Thank you.

**Comment by Carlmundo** [comment]
Hi Ben,

Apologies for the delay. I've credited you in the readme under the name "Squirminator2k". If you want this changed then please let me know.

**Comment by BenPaddon** [comment]
That's perfect, thank you!
