### ISSUE TITLE
Quick Game doesn't correctly set the in-game screen resolution

### ISSUE THREAD

**Issue by HeyItsLollie** [Carlmundo/W2-Plus#9]
Upon opening Worms 2, if you start a new local match via one of the two Quick Game buttons, the in-game window will be much smaller than the screen's current resolution.

![worms2 - 2023-10-21 - 16-04-08](https://github.com/Carlmundo/W2-Plus/assets/30498581/33c86d67-fce6-45cf-aefb-b7ced5fef00b)

Workaround: Enter the Custom Game menu, and then return to the main menu. Quick Game will now fill the screen as expected.

Windows 11 Pro, Version 22H2, Build 22621.2428
Worms 2 via GOG, using W2-Plus v1.5.6.

**Comment by Carlmundo** [comment]
Cavern maps are limited to these resolutions. You can however, scroll in on the mouse to zoom in as a workaround.

**Comment by HeyItsLollie** [comment]
Aha, I hadn't realized this was specifically a cavern map issue, I just didn't know about the zoom feature. Sure enough, when it loads an open map from first boot, it looks correct. I'll close this as it is functioning correctly.

**Comment by Carlmundo** [comment]
@HeyItsLollie I have a fix for this in the latest beta version, please see: https://github.com/Carlmundo/W2-Plus/issues/11#issuecomment-1862777955
